CREATE DATABASE wordpress;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'MARIADB_ROOT_PASS';

CREATE USER 'MARIADB_SP_USER'@'%' IDENTIFIED BY 'MARIADB_ROOT_PASS';
GRANT ALL PRIVILEGES ON wordpress.* TO 'MARIADB_SP_USER'@'%';

CREATE USER 'MARIADB_USER'@'%' IDENTIFIED BY 'MARIADB_U_PASS';
GRANT SELECT ON wordpress.* TO 'MARIADB_USER'@'%';
GRANT INSERT ON wordpress.* TO 'MARIADB_USER'@'%';
FLUSH PRIVILEGES;
