CREATE DATABASE wordpress;
CREATE USER '${MARIADB_USER}'@'%' IDENTIFIED BY '${MARIADB_U_PASS}';
GRANT ALL PRIVILEGES ON wordpress.* TO '${MARIADB_USER}'@'%';
FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY '${MARIADB_ROOT_PASS}';
