CREATE DATABASE wordpress;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'MARIADB_U_PASS';
CREATE USER 'MARIADB_USER'@'%' IDENTIFIED BY 'MARIADB_U_PASS';
GRANT ALL PRIVILEGES ON wordpress.* TO 'MARIADB_USER'@'%';
FLUSH PRIVILEGES;
